let handler = async (m, { command }) => {

 const persen = Math.floor(Math.random() * 101)

 const teks = {
  cekhoki: "Tingkat hoki kamu",
  cekrezeki: "Rezeki kamu hari ini",
  cekapes: "Tingkat kesialan",
  cekberuntung: "Keberuntungan",
  cekkarma: "Karma kamu",
  cekdosa: "Dosa kamu",
  cekpahala: "Pahala kamu",
  cekiman: "Iman kamu",
  cekaura: "Aura kamu",
  cekganteng: "Kegantengan",
  cekcantik: "Kecantikan",
  cekmiskin: "Kemiskinan",
  cekkaya: "Kekayaan",
  cekjodoh: "Jodoh kamu",
  cekjomblo: "Nasib jomblo",
  cekpacar: "Potensi punya pacar",
  ceknikah: "Peluang nikah",
  cekstress: "Tingkat stress",
  cekbahagia: "Kebahagiaan",
  cekmalas: "Kemalasan",
  cekrajin: "Kerajinan",
  cekpintar: "Kepintaran",
  cekbodoh: "Kebodohan",
  cekwaras: "Kewarasan",
  cekgila: "Kegilaan",
  cekhalu: "Tingkat halu",
  cekgabut: "Tingkat kegabutan",
  cekwibu: "Level wibu",
  cekotaku: "Level otaku",
  cekpro: "Skill pro",
  ceknoob: "Level noob",
  cekskill: "Skill gaming",
  cekrank: "Rank gamer",
  ceklevel: "Level kehidupan",
  cekpower: "Power kamu",
  cekmental: "Mental kamu",
  cektoxic: "Tingkat toxic",
  cekbaik: "Kebaikan",
  cekjahat: "Kejahatan",
  ceksetan: "Aura setan",
  cekmalaikat: "Aura malaikat",
  cekiblis: "Aura iblis",
  cekustadz: "Aura ustadz",
  cekalim: "Kealiman",
  cektajir: "Ketajiran",
  cekboss: "Aura boss",
  ceksultan: "Aura sultan",
  ceknpc: "Aura NPC",
  ceksigma: "Aura sigma",
  cekalpha: "Aura alpha",
  cekbeta: "Aura beta",
  cekomega: "Aura omega",
  cekbadut: "Level badut",
  cekbeban: "Level beban",
  cekkeren: "Kekerenan",
  ceklegend: "Level legend",
  cekepic: "Level epic",
  cekrare: "Level rare",
  cekmythic: "Level mythic",
  cekgod: "Level dewa",
  cekiblismode: "Mode iblis",
  cekmager: "Tingkat mager",
  cekaktif: "Keaktifan",
  ceknolep: "No life meter",
  cekintrovert: "Introvert level",
  cekextrovert: "Extrovert level",
  cekjulid: "Tingkat julid",
  cekbucin: "Level bucin",
  cekromantis: "Keromantisan",
  cekdingin: "Kedinginan hati",
  cekpanas: "Kepanasan",
  cekgreget: "Tingkat greget",
  cekmenyala: "Aura menyala",
  cekgelap: "Aura gelap",
  cekterang: "Aura terang",
  cekluck: "Luck kamu",
  cekfortune: "Fortune kamu",
  cekfate: "Fate kamu",
  cekdestiny: "Destiny kamu",
  cekvision: "Vision kamu",
  cekfuture: "Masa depan",
  cekpast: "Masa lalu",
  cekpresent: "Masa kini",
  cekotak: "Kecerdasan otak",
  cekhati: "Kebaikan hati",
  cekjiwa: "Kekuatan jiwa",
  ceknyali: "Nyali kamu",
  cekberani: "Keberanian",
  cekpenakut: "Ketakutan",
  cekmisterius: "Kemisteriusan",
  cekpopuler: "Popularitas",
  cekterkenal: "Ketenaran",
  cekviral: "Potensi viral",
  cekfamous: "Famous meter",
  cekinfluencer: "Aura influencer",
  cekkonten: "Bakat konten",
  cekstreamer: "Aura streamer",
  cekprogrammer: "Skill ngoding",
  cekdeveloper: "Level developer",
  cekhacker: "Skill hacker",
  cekotaklicik: "Kel licikan",
  cekcerdik: "Kecerdikan",
  cekstrategi: "Strategi",
  cekgaming: "Skill gaming",
  cekfps: "Skill FPS",
  cekmoba: "Skill MOBA",
  cekmmr: "MMR kamu",
  cekrankgame: "Rank game",
  cekcarry: "Kemampuan carry",
  cektroll: "Level troll",
  cekfeed: "Level feeder",
  cekwinrate: "Winrate hidup",
  cekmvp: "Peluang MVP",
  cekafk: "Level AFK",
  cekgrind: "Grind level",
  cekpekerja: "Kerja keras",
  cekpengangguran: "Aura pengangguran",
  cekusaha: "Aura usaha",
  cekstartup: "Aura startup",
  cekbosbesar: "Aura bos besar",
  cekmiliarder: "Potensi miliarder",
  cektriliuner: "Potensi triliuner"
 }

 const hasil = teks[command] || "Status kamu"
 
 await m.reply(`🔎 ${hasil}: *${persen}%*`)
}

handler.help = [
"cekhoki","cekrezeki","cekapes","cekberuntung","cekkarma","cekdosa","cekpahala","cekiman","cekaura",
"cekganteng","cekcantik","cekmiskin","cekkaya","cekjodoh","cekjomblo","cekpacar","ceknikah",
"cekstress","cekbahagia","cekmalas","cekrajin","cekpintar","cekbodoh","cekwaras","cekgila",
"cekhalu","cekgabut","cekwibu","cekotaku","cekpro","ceknoob","cekskill","cekrank","ceklevel",
"cekpower","cekmental","cektoxic","cekbaik","cekjahat","ceksetan","cekmalaikat","cekiblis",
"cekustadz","cekalim","cektajir","cekboss","ceksultan","ceknpc","ceksigma","cekalpha","cekbeta",
"cekomega","cekbadut","cekbeban","cekkeren","ceklegend","cekepic","cekrare","cekmythic","cekgod",
"cekiblismode","cekmager","cekaktif","ceknolep","cekintrovert","cekextrovert","cekjulid","cekbucin",
"cekromantis","cekdingin","cekpanas","cekgreget","cekmenyala","cekgelap","cekterang","cekluck",
"cekfortune","cekfate","cekdestiny","cekvision","cekfuture","cekpast","cekpresent","cekotak",
"cekhati","cekjiwa","ceknyali","cekberani","cekpenakut","cekmisterius","cekpopuler","cekterkenal",
"cekviral","cekfamous","cekinfluencer","cekkonten","cekstreamer","cekprogrammer","cekdeveloper",
"cekhacker","cekotaklicik","cekcerdik","cekstrategi","cekgaming","cekfps","cekmoba","cekmmr",
"cekrankgame","cekcarry","cektroll","cekfeed","cekwinrate","cekmvp","cekafk","cekgrind",
"cekpekerja","cekpengangguran","cekusaha","cekstartup","cekbosbesar","cekmiliarder","cektriliuner"
]

handler.tags = ["fun"]
handler.command = [
"cekhoki","cekrezeki","cekapes","cekberuntung","cekkarma","cekdosa","cekpahala","cekiman","cekaura",
"cekganteng","cekcantik","cekmiskin","cekkaya","cekjodoh","cekjomblo","cekpacar","ceknikah",
"cekstress","cekbahagia","cekmalas","cekrajin","cekpintar","cekbodoh","cekwaras","cekgila",
"cekhalu","cekgabut","cekwibu","cekotaku","cekpro","ceknoob","cekskill","cekrank","ceklevel",
"cekpower","cekmental","cektoxic","cekbaik","cekjahat","ceksetan","cekmalaikat","cekiblis",
"cekustadz","cekalim","cektajir","cekboss","ceksultan","ceknpc","ceksigma","cekalpha","cekbeta",
"cekomega","cekbadut","cekbeban","cekkeren","ceklegend","cekepic","cekrare","cekmythic","cekgod",
"cekiblismode","cekmager","cekaktif","ceknolep","cekintrovert","cekextrovert","cekjulid","cekbucin",
"cekromantis","cekdingin","cekpanas","cekgreget","cekmenyala","cekgelap","cekterang","cekluck",
"cekfortune","cekfate","cekdestiny","cekvision","cekfuture","cekpast","cekpresent","cekotak",
"cekhati","cekjiwa","ceknyali","cekberani","cekpenakut","cekmisterius","cekpopuler","cekterkenal",
"cekviral","cekfamous","cekinfluencer","cekkonten","cekstreamer","cekprogrammer","cekdeveloper",
"cekhacker","cekotaklicik","cekcerdik","cekstrategi","cekgaming","cekfps","cekmoba","cekmmr",
"cekrankgame","cekcarry","cektroll","cekfeed","cekwinrate","cekmvp","cekafk","cekgrind",
"cekpekerja","cekpengangguran","cekusaha","cekstartup","cekbosbesar","cekmiliarder","cektriliuner"
]
handler.register = true

export default handler